---
name: ShellCheck

# yamllint disable-line rule:truthy
on:
  push:
    paths: ['**/*.sh']
  pull_request:
    paths: ['**/*.sh']
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
...
