---
name: Validate Blueprint YAML

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "nspanel_easy_blueprint.yaml"
  pull_request:
    paths:
      - "nspanel_easy_blueprint.yaml"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate Blueprint YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Validate nspanel_easy_blueprint.yaml
        run: yamllint -c "./.rules/yamllint.yml" nspanel_easy_blueprint.yaml
...
